// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/hakuna86/golang-token-auth-server-sample/ent/article"
	"github.com/hakuna86/golang-token-auth-server-sample/ent/auth"
	"github.com/hakuna86/golang-token-auth-server-sample/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	created_at *time.Time
	updated_at *time.Time
	email      *string
	username   *string
	password   *string
	role       *string
	auth       map[int]struct{}
	articles   map[int]struct{}
}

// SetCreatedAt sets the created_at field.
func (uc *UserCreate) SetCreatedAt(t time.Time) *UserCreate {
	uc.created_at = &t
	return uc
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (uc *UserCreate) SetNillableCreatedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// SetUpdatedAt sets the updated_at field.
func (uc *UserCreate) SetUpdatedAt(t time.Time) *UserCreate {
	uc.updated_at = &t
	return uc
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (uc *UserCreate) SetNillableUpdatedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetUpdatedAt(*t)
	}
	return uc
}

// SetEmail sets the email field.
func (uc *UserCreate) SetEmail(s string) *UserCreate {
	uc.email = &s
	return uc
}

// SetUsername sets the username field.
func (uc *UserCreate) SetUsername(s string) *UserCreate {
	uc.username = &s
	return uc
}

// SetPassword sets the password field.
func (uc *UserCreate) SetPassword(s string) *UserCreate {
	uc.password = &s
	return uc
}

// SetRole sets the role field.
func (uc *UserCreate) SetRole(s string) *UserCreate {
	uc.role = &s
	return uc
}

// SetAuthID sets the auth edge to Auth by id.
func (uc *UserCreate) SetAuthID(id int) *UserCreate {
	if uc.auth == nil {
		uc.auth = make(map[int]struct{})
	}
	uc.auth[id] = struct{}{}
	return uc
}

// SetNillableAuthID sets the auth edge to Auth by id if the given value is not nil.
func (uc *UserCreate) SetNillableAuthID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetAuthID(*id)
	}
	return uc
}

// SetAuth sets the auth edge to Auth.
func (uc *UserCreate) SetAuth(a *Auth) *UserCreate {
	return uc.SetAuthID(a.ID)
}

// AddArticleIDs adds the articles edge to Article by ids.
func (uc *UserCreate) AddArticleIDs(ids ...int) *UserCreate {
	if uc.articles == nil {
		uc.articles = make(map[int]struct{})
	}
	for i := range ids {
		uc.articles[ids[i]] = struct{}{}
	}
	return uc
}

// AddArticles adds the articles edges to Article.
func (uc *UserCreate) AddArticles(a ...*Article) *UserCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return uc.AddArticleIDs(ids...)
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if uc.created_at == nil {
		v := user.DefaultCreatedAt()
		uc.created_at = &v
	}
	if uc.updated_at == nil {
		v := user.DefaultUpdatedAt()
		uc.updated_at = &v
	}
	if uc.email == nil {
		return nil, errors.New("ent: missing required field \"email\"")
	}
	if uc.username == nil {
		return nil, errors.New("ent: missing required field \"username\"")
	}
	if uc.password == nil {
		return nil, errors.New("ent: missing required field \"password\"")
	}
	if uc.role == nil {
		return nil, errors.New("ent: missing required field \"role\"")
	}
	if len(uc.auth) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"auth\"")
	}
	return uc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	var (
		res     sql.Result
		builder = sql.Dialect(uc.driver.Dialect())
		u       = &User{config: uc.config}
	)
	tx, err := uc.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	insert := builder.Insert(user.Table).Default()
	if value := uc.created_at; value != nil {
		insert.Set(user.FieldCreatedAt, *value)
		u.CreatedAt = *value
	}
	if value := uc.updated_at; value != nil {
		insert.Set(user.FieldUpdatedAt, *value)
		u.UpdatedAt = *value
	}
	if value := uc.email; value != nil {
		insert.Set(user.FieldEmail, *value)
		u.Email = *value
	}
	if value := uc.username; value != nil {
		insert.Set(user.FieldUsername, *value)
		u.Username = *value
	}
	if value := uc.password; value != nil {
		insert.Set(user.FieldPassword, *value)
		u.Password = *value
	}
	if value := uc.role; value != nil {
		insert.Set(user.FieldRole, *value)
		u.Role = *value
	}

	id, err := insertLastID(ctx, tx, insert.Returning(user.FieldID))
	if err != nil {
		return nil, rollback(tx, err)
	}
	u.ID = int(id)
	if len(uc.auth) > 0 {
		eid := keys(uc.auth)[0]
		query, args := builder.Update(user.AuthTable).
			Set(user.AuthColumn, id).
			Where(sql.EQ(auth.FieldID, eid).And().IsNull(user.AuthColumn)).
			Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return nil, rollback(tx, err)
		}
		affected, err := res.RowsAffected()
		if err != nil {
			return nil, rollback(tx, err)
		}
		if int(affected) < len(uc.auth) {
			return nil, rollback(tx, &ErrConstraintFailed{msg: fmt.Sprintf("one of \"auth\" %v already connected to a different \"User\"", keys(uc.auth))})
		}
	}
	if len(uc.articles) > 0 {
		p := sql.P()
		for eid := range uc.articles {
			p.Or().EQ(article.FieldID, eid)
		}
		query, args := builder.Update(user.ArticlesTable).
			Set(user.ArticlesColumn, id).
			Where(sql.And(p, sql.IsNull(user.ArticlesColumn))).
			Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return nil, rollback(tx, err)
		}
		affected, err := res.RowsAffected()
		if err != nil {
			return nil, rollback(tx, err)
		}
		if int(affected) < len(uc.articles) {
			return nil, rollback(tx, &ErrConstraintFailed{msg: fmt.Sprintf("one of \"articles\" %v already connected to a different \"User\"", keys(uc.articles))})
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return u, nil
}
