// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
